// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0-nkaz4g63y8NsuJ_mFCfcdEA23EhboY',
    appId: '1:1078190362460:web:b9ccedd701e695db9dbb99',
    messagingSenderId: '1078190362460',
    projectId: 'agriculture-app-55577',
    authDomain: 'agriculture-app-55577.firebaseapp.com',
    storageBucket: 'agriculture-app-55577.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8nrNXwPKw7NqQf1UFgwvU1WuxIlNDEQ',
    appId: '1:1078190362460:android:9fb0295905b427f99dbb99',
    messagingSenderId: '1078190362460',
    projectId: 'agriculture-app-55577',
    storageBucket: 'agriculture-app-55577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNx2jdjAQG9tap4InVEjXoRJCAGH4DsDI',
    appId: '1:1078190362460:ios:4edfcc4fe57a11d79dbb99',
    messagingSenderId: '1078190362460',
    projectId: 'agriculture-app-55577',
    storageBucket: 'agriculture-app-55577.appspot.com',
    iosClientId: '1078190362460-96n2j6lesp57m95t4sg6h4qi590gjbj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.agricultureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNx2jdjAQG9tap4InVEjXoRJCAGH4DsDI',
    appId: '1:1078190362460:ios:4edfcc4fe57a11d79dbb99',
    messagingSenderId: '1078190362460',
    projectId: 'agriculture-app-55577',
    storageBucket: 'agriculture-app-55577.appspot.com',
    iosClientId: '1078190362460-96n2j6lesp57m95t4sg6h4qi590gjbj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.agricultureApp',
  );
}
